// Renders the MOSAIC figures authored in gallery.html to theme-adaptive SVG for
// the MkDocs site. Figures are embedded inline and coloured by page tokens, so we
// emit the raw var(--m-*) markup (portable:false) and generate a token bridge that
// maps the pinned library's own palette onto Material's light/dark schemes. No SVG
// coordinates are authored here and no library source is copied — everything is
// derived from the pinned @mosaic/technical-graphics package.
import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile, stat, mkdir, writeFile} from 'node:fs/promises';
import {extname, join, resolve} from 'node:path';

const ROOT = resolve('.');
const SVG_OUT = resolve('../docs/figures/svg');
const CSS_OUT = resolve('../docs/stylesheets/mosaic-tokens.css');
const PKG = 'node_modules/@mosaic/technical-graphics';
const SEL = 'mosaic-process,mosaic-reel-timeline,mosaic-workflow,mosaic-frame-sequence';
const TYPES = {'.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml', '.json': 'application/json'};

// --- 1. Token bridge: pull the library's palette, map to Material's schemes ---
function block(css, selector) {
  const start = css.indexOf(selector);
  const open = css.indexOf('{', start), close = css.indexOf('}', open);
  return css.slice(open + 1, close).trim();
}
const tokensCss = await readFile(join(PKG, 'src/tokens.css'), 'utf8');
const light = block(tokensCss, ':root {');
const dark = block(tokensCss, ':root[data-theme="dark"] {');
await mkdir(resolve('../docs/stylesheets'), {recursive: true});
await writeFile(CSS_OUT,
`/* GENERATED by graphics/build.mjs from @mosaic/technical-graphics tokens.css — do not edit. */
[data-md-color-scheme="default"] {\n  ${light}\n}
[data-md-color-scheme="slate"] {\n  ${dark}\n}
.mosaic-fig { margin: 1.6em 0; }
.mosaic-fig svg { display: block; width: 100%; height: auto; }
`);
console.log('wrote', CSS_OUT);

// --- 2. Render the authored figures to host-themed SVG ---
const server = createServer(async (req, res) => {
  try {
    let p = join(ROOT, decodeURIComponent(req.url.split('?')[0]));
    if ((await stat(p)).isDirectory()) p = join(p, 'index.html');
    res.setHeader('content-type', TYPES[extname(p)] || 'application/octet-stream');
    res.setHeader('cache-control', 'no-store');
    res.end(await readFile(p));
  } catch { res.statusCode = 404; res.end('Not found'); }
}).listen(4180);
await mkdir(SVG_OUT, {recursive: true});
try {
  const browser = await chromium.launch({headless: true});
  const page = await browser.newPage({viewport: {width: 1440, height: 1400}});
  const errors = [];
  page.on('pageerror', e => errors.push(String(e)));
  await page.goto('http://localhost:4180/gallery.html');
  await page.waitForSelector('mosaic-process');
  if (errors.length) throw new Error('Page errors: ' + errors.join('; '));
  const names = await page.$$eval(SEL, els => els.map(e => e.dataset.name));
  for (let i = 0; i < names.length; i++) {
    if (!names[i]) throw new Error(`Figure ${i} is missing a data-name`);
    const svg = await page.evaluate(({sel, idx}) => document.querySelectorAll(sel)[idx].toSVG({portable: false}), {sel: SEL, idx: i});
    await writeFile(join(SVG_OUT, names[i] + '.svg'), svg);
    console.log('wrote', names[i] + '.svg');
  }
  await browser.close();
} finally {
  server.close();
}
